require('flyingmt.gitsigns')
require('flyingmt.lualine')
require('flyingmt.nvim-tree')
require('flyingmt.lsp')
require('flyingmt.telescope')
require('flyingmt.treesitter')
require('flyingmt.bufferline')
